export enum code {
    EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
    USER_REGISTERED = 'USER_REGISTERED',
    VERIFY_EMAIL = 'VERIFY_EMAIL',
    EMAIL_VERIFIED = 'EMAIL_VERIFIED',
    PASSWORD_UPDATED = 'PASSWORD_UPDATED',
    ERROR_GENERIC = "ERROR_GENERIC",
    NOT_FOUND_USER = "NOT_FOUND_USER",
    UID_ALREADY_IN_USE = "UID_ALREADY_IN_USE",
    PROVIDERS_USER_IS_INVALID = "PROVIDERS_USER_IS_INVALID",
    USER_UPDATED = "USER_UPDATED"
}