export enum code {
    EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
    USER_REGISTERED = 'AUTH_USER_REGISTERED',
    VERIFY_EMAIL = 'AUTH_VERIFY_EMAIL',
    EMAIL_VERIFIED = 'AUTH_EMAIL_VERIFIED',
    PASSWORD_UPDATED = 'AUTH_PASSWORD_UPDATED',
    ERROR_GENERIC = "ERROR_GENERIC",
    NOT_FOUND_USER = "NOT_FOUND_USER",
    UID_ALREADY_IN_USE = "UID_ALREADY_IN_USE",
    
}